Termo de uso
SharebookBR/sharebook-frontend pull request #312
Opened 2020-10-13 23:57 UTC by Jordangabriel893

2020-10-14 03:14 UTC, wantero requested changes
@Jordangabriel893 parabéns pela sua primeira PR no Sharebook. Pedi somente uns pequenos ajustes. Caso tenha qualquer dúvida, fique a vontade de me contactar para lhe ajudar no seu processo de aprendizado dentro do projeto.

2020-10-14 03:14 UTC, wantero commented on src/app/app.module.ts
> +import { TermOfUseComponent } from './components/term-of-use/term-of-use.component';
@Jordangabriel893, vamos usar o nome TermsOfUse com o "s" no final do Terms?

2020-10-14 03:14 UTC, wantero commented on src/app/components/footer/footer.component.html
> +            <a routerLink="/termo-uso">Termo de uso</a>
Que tal usarmos Termo**s** de uso? Visto que o termo de uso é composto de vários termos.

2020-10-14 03:14 UTC, wantero commented on src/app/components/register/register.component.html
> +          <input class="form-check-input" type="checkbox" formControlName="aceptTermOfUse" id="defaultCheck2" required
Faltou um "c" no accept. Que tal também incluir o "s" no term (acceptTermsOfUse)?

2020-10-14 03:14 UTC, wantero commented on src/app/components/register/register.component.html
> +            Aceito os <a href="http://localhost:4200/termo-uso">termos de uso</a>
**href** deve apontar para a rota do componente. Aqui está com a URL apontando para localhost e quando subirmos para o ambiente de DEV, STG ou PROD, o mesmo não irá funcionar.

2020-10-14 03:14 UTC, wantero commented on src/app/components/register/register.component.html
> +</form>
Adicionar quebra de linha no final do arquivo.

2020-10-14 03:14 UTC, wantero commented on src/app/components/register/register.component.ts
> +      aceptTermOfUse: [true, null],
Usar acceptTermsOfUse. O default deveria ser false, assim o usuário precisará marcar que aceitou os termos de uso.

2020-10-14 03:14 UTC, wantero commented on src/app/components/term-of-use/term-of-use.component.spec.ts
> +import { TermOfUseComponent } from './term-of-use.component';
Ajustar esse arquivo de teste para o nome solicitado de componente TermsOfUse.

2020-10-14 03:14 UTC, wantero commented on src/app/components/term-of-use/term-of-use.component.ts
> +  selector: 'app-term-of-use',
Utilizar também como terms-of-use.

2020-10-14 03:14 UTC, wantero commented on src/app/core/app-routing.module.ts
> +import { TermOfUseComponent } from './../components/term-of-use/term-of-use.component';
Adequar a palavra Terms.

2020-10-14 03:14 UTC, wantero commented on src/app/core/app-routing.module.ts
> +    path: 'termo-uso',
Quel tal usarmos a rota termos-de-uso ? Fica mais explícito.

2020-11-03 22:45 UTC, raffacabofrio approved these changes

2020-11-03 22:46 UTC, merged