Mostra meetups na home.
SharebookBR/sharebook-frontend pull request #407
Opened 2022-06-16 20:21 UTC by raffacabofrio

2022-06-18 15:09 UTC, wantero commented
@raffacabofrio PR foi bloqueada pelo SonarCloud. Consegue corrigir os pontos apontados?

2022-06-18 17:32 UTC, raffacabofrio commented
@wantero ajustes efetuados. Sonar 100% agora. =)

2022-06-21 02:16 UTC, wantero requested changes

2022-06-21 02:16 UTC, wantero commented on src/app/components/home/home.component.ts
> +        console.log(this.meetups);
Remover esse console.log

2022-06-21 12:48 UTC, wantero approved these changes

2022-06-21 12:48 UTC, merged