Ao clicar no meetup, abrir o sympla caso o evento ainda não tenha…
SharebookBR/sharebook-frontend pull request #455
Opened 2023-01-25 19:29 UTC by raffacabofrio

começado.

2023-01-25 19:44 UTC, wantero requested changes
Atualizar os dockerfile.

2023-01-25 19:44 UTC, wantero commented on src/app/components/card-meetup/card-meetup.component.html
> +  <a href="javascript:void(0)" (click)="OpenMeetup()">
Será que não dá para chamar direto o método GetMeetupUrl aqui no href?

2023-01-25 20:53 UTC, raffacabofrio commented on src/app/components/card-meetup/card-meetup.component.html
> +  <a href="javascript:void(0)" (click)="OpenMeetup()">
dá sim. feito.

2023-01-26 14:37 UTC, wantero approved these changes

2023-01-26 14:40 UTC, merged